# Generated by Django 4.2.7 on 2023-11-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='iamge',
            new_name='image',
        ),
    ]
