# Generated by Django 4.2.7 on 2023-12-06 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_artist_image_artist_inst_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='painting',
            name='support',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.support'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='technique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.technique'),
        ),
    ]
