# Generated by Django 4.2.7 on 2023-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_support_technique_alter_painting_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='pheight',
            field=models.DecimalField(decimal_places=2, default=23.5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='pwidth',
            field=models.DecimalField(decimal_places=2, default=19.25, max_digits=10),
            preserve_default=False,
        ),
    ]
