# Generated by Django 4.2.7 on 2023-12-08 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_painting_pheight_painting_pwidth'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
