# Generated by Django 4.2.7 on 2023-12-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_painting_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
