# Generated by Django 4.2.7 on 2023-12-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_painting_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
