# Generated by Django 4.2.7 on 2024-01-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_artist_bio_alter_painting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/painting/'),
        ),
        migrations.AddField(
            model_name='painting',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/painting/'),
        ),
        migrations.AddField(
            model_name='painting',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/painting/'),
        ),
    ]
