# Generated by Django 4.2.7 on 2024-01-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_painting_image2_painting_image3_painting_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
