# Generated by Django 4.2.7 on 2024-02-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_painting_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painting',
            options={'ordering': ('-pub_date',)},
        ),
    ]
