# Generated by Django 4.2.7 on 2024-03-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_painting_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='image4',
        ),
        migrations.AddField(
            model_name='artist',
            name='fcbk_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='sing_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/artist/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='x_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
