# Generated by Django 4.2.7 on 2024-03-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_painting_image2_remove_painting_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
