# Generated by Django 4.2.7 on 2024-03-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_artist_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='url',
            new_name='web_url',
        ),
        migrations.AlterField(
            model_name='artist',
            name='inst_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
