# Generated by Django 4.2.7 on 2024-03-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_artist_fcbk_url_alter_artist_web_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
