# Generated by Django 4.2.7 on 2024-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_painting_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
